#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# output format
# ------------------------------------------------------------------------------
out() {
    printf "\n"

    while IFS= read -r line; do
        printf "\033[0;31m>>>\033[0m \033[0;33m%s\033[0m\n" "$line"
    done
}

# ------------------------------------------------------------------------------
# trap on_exit
# ------------------------------------------------------------------------------
function on_exit {
    if [[ "$COMPLETED" != true ]]; then
        out <<< "Something went wrong. Not completed!"
        exit 1
    else
        out <<EOF
Installation Duration: $DURATION
Completed successfully!
EOF

        exit 0
    fi
}

COMPLETED=false
trap on_exit EXIT

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
export APT_PROXY_OPTION=$APT_PROXY_OPTION
export DEBIAN_FRONTEND=noninteractive
export START_TIME=$(date +%s)
export BASEDIR=$(pwd)
export TMPL=https://raw.githubusercontent.com/jitsi-contrib/jitas/main/templates/debian-buster-mate

# ------------------------------------------------------------------------------
# packages
# ------------------------------------------------------------------------------
out <<< "installing packages..."

for i in $(seq 3); do
    apt-get -y --allow-releaseinfo-change update && sleep 3 && break
done

apt-get $APT_PROXY_OPTION -y install apt-utils \
    -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold"
apt-get $APT_PROXY_OPTION -y upgrade \
    -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold"
apt-get -y autoremove --purge

apt-get $APT_PROXY_OPTION -y install apt-transport-https gnupg
apt-get $APT_PROXY_OPTION -y install wget curl
apt-get $APT_PROXY_OPTION -y install tmux vim ack jq rsync htop
apt-get $APT_PROXY_OPTION -y install ssl-cert ca-certificates openssl certbot
apt-get $APT_PROXY_OPTION -y install task-desktop task-mate-desktop dconf-cli
apt-get $APT_PROXY_OPTION -y install chromium
apt-get $APT_PROXY_OPTION -y install x11vnc pwgen git
apt-get $APT_PROXY_OPTION -y install nginx
apt-get $APT_PROXY_OPTION -y install python3-pip python3-setuptools \
    python3-wheel

pip3 install websockify

# ------------------------------------------------------------------------------
# disabled services
# ------------------------------------------------------------------------------
out <<< "disabling some desktop services..."

systemctl stop lightdm.service
systemctl disable lightdm.service

systemctl stop ModemManager.service
systemctl disable ModemManager.service

systemctl stop wpa_supplicant.service
systemctl disable wpa_supplicant.service

systemctl stop NetworkManager.service
systemctl disable NetworkManager.service

# ------------------------------------------------------------------------------
# dconf
# ------------------------------------------------------------------------------
out <<< "dconf configuration..."

mkdir -p /etc/dconf/profile
mkdir -p /etc/dconf/db/jitas.d

wget -O /etc/dconf/profile/user $TMPL/etc/dconf/profile/user
wget -O /etc/dconf/db/jitas.d/disable-log-out \
    $TMPL/etc/dconf/db/jitas.d/disable-log-out
wget -O /etc/dconf/db/jitas.d/disable-user-switching \
    $TMPL/etc/dconf/db/jitas.d/disable-user-switching
wget -O /etc/dconf/db/jitas.d/disable-lock-screen \
    $TMPL/etc/dconf/db/jitas.d/disable-lock-screen
wget -O /etc/dconf/db/jitas.d/screensaver \
    $TMPL/etc/dconf/db/jitas.d/screensaver
wget -O /etc/dconf/db/jitas.d/click-policy \
    $TMPL/etc/dconf/db/jitas.d/click-policy

dconf update

# ------------------------------------------------------------------------------
# x11vnc autostart
# ------------------------------------------------------------------------------
out <<< "x11vnc autostart..."

wget -O /usr/local/bin/vnc-start \
    $TMPL/usr/local/bin/vnc-start
wget -O /etc/xdg/autostart/vnc.desktop \
    $TMPL/etc/xdg/autostart/vnc.desktop

chmod +x /usr/local/bin/vnc-start

# ------------------------------------------------------------------------------
# user jitas
# ------------------------------------------------------------------------------
out <<< "jitas account..."

# adduser jitas
id jitas 2>/dev/null || adduser jitas --disabled-password --gecos ""

# autostart desktop for jitas
[[ -f /home/jitas/.bashrc ]] || false

grep 'exec startx' /home/jitas/.bashrc || cat >>/home/jitas/.bashrc <<EOF

if [[ -z \$DISPLAY ]] && [[ \$(tty) = /dev/tty1 ]]; then
    exec startx
    exit
fi
EOF

# disable some autostarted applications for jitas
mkdir -p /home/jitas/.config/autostart
wget -O /home/jitas/.config/autostart/mate-power-manager.desktop \
    $TMPL/home/jitas/.config/autostart/mate-power-manager.desktop
wget -O /home/jitas/.config/autostart/mate-screensaver.desktop \
    $TMPL/home/jitas/.config/autostart/mate-screensaver.desktop
wget -O /home/jitas/.config/autostart/nm-applet.desktop \
    $TMPL/home/jitas/.config/autostart/nm-applet.desktop
chown jitas:jitas /home/jitas/.config/autostart -R

# vnc password
mkdir -p /home/jitas/.vnc
PASSWD=$(pwgen -B 12)
x11vnc -storepasswd $PASSWD /home/jitas/.vnc/passwd
chown jitas:jitas /home/jitas/.vnc -R

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
END_TIME=$(date +%s)
DURATION=$(date -u -d "0 $END_TIME seconds - $START_TIME seconds" +"%H:%M:%S")
COMPLETED=true
