#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# output format
# ------------------------------------------------------------------------------
out() {
    printf "\n"

    while IFS= read -r line; do
        printf "\033[0;31m>>>\033[0m \033[0;33m%s\033[0m\n" "$line"
    done
}

# ------------------------------------------------------------------------------
# trap on_exit
# ------------------------------------------------------------------------------
function on_exit {
    if [[ "$COMPLETED" != true ]]; then
        out <<< "Something went wrong. Not completed!"
        exit 1
    else
        out <<EOF
Installation Duration: $DURATION
Completed successfully!
EOF

        if [ "$ACTIVE_SESSION" = true ]; then
            out <<EOF
It's detected an already running session. Please reboot!
EOF

        exit 0
    fi
}

COMPLETED=false
trap on_exit EXIT

# ------------------------------------------------------------------------------
# environment
# ------------------------------------------------------------------------------
export APT_PROXY_OPTION=$APT_PROXY_OPTION
export DEBIAN_FRONTEND=noninteractive
export START_TIME=$(date +%s)
export BASEDIR=$(pwd)
export TMPL=https://raw.githubusercontent.com/jitsi-contrib/jitas/main/templates/debian-buster-mate

# ------------------------------------------------------------------------------
# packages
# ------------------------------------------------------------------------------
out <<< "installing packages..."

for i in $(seq 3); do
    apt-get -y --allow-releaseinfo-change update && sleep 3 && break
done

apt-get $APT_PROXY_OPTION -y install apt-utils \
    -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold"
apt-get $APT_PROXY_OPTION -y upgrade \
    -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold"
apt-get -y autoremove --purge

apt-get $APT_PROXY_OPTION -y install apt-transport-https gnupg
apt-get $APT_PROXY_OPTION -y install wget curl
apt-get $APT_PROXY_OPTION -y install tmux vim ack jq rsync htop
apt-get $APT_PROXY_OPTION -y install ssl-cert ca-certificates openssl certbot
apt-get $APT_PROXY_OPTION -y install task-desktop task-mate-desktop dconf-cli
apt-get $APT_PROXY_OPTION -y install chromium
apt-get $APT_PROXY_OPTION -y install x11vnc pwgen git
apt-get $APT_PROXY_OPTION -y install nginx
apt-get $APT_PROXY_OPTION -y install python3-pip python3-setuptools \
    python3-wheel

pip3 install websockify

# ------------------------------------------------------------------------------
# disabled services
# ------------------------------------------------------------------------------
out <<< "disabling some desktop services..."

systemctl stop lightdm.service
systemctl disable lightdm.service

systemctl stop ModemManager.service
systemctl disable ModemManager.service

systemctl stop wpa_supplicant.service
systemctl disable wpa_supplicant.service

systemctl stop NetworkManager.service
systemctl disable NetworkManager.service

# ------------------------------------------------------------------------------
# dconf
# ------------------------------------------------------------------------------
out <<< "dconf configuration..."

mkdir -p /etc/dconf/profile
mkdir -p /etc/dconf/db/jitas.d

wget -O /etc/dconf/profile/user $TMPL/etc/dconf/profile/user
wget -O /etc/dconf/db/jitas.d/disable-log-out \
    $TMPL/etc/dconf/db/jitas.d/disable-log-out
wget -O /etc/dconf/db/jitas.d/disable-user-switching \
    $TMPL/etc/dconf/db/jitas.d/disable-user-switching
wget -O /etc/dconf/db/jitas.d/disable-lock-screen \
    $TMPL/etc/dconf/db/jitas.d/disable-lock-screen
wget -O /etc/dconf/db/jitas.d/screensaver \
    $TMPL/etc/dconf/db/jitas.d/screensaver
wget -O /etc/dconf/db/jitas.d/click-policy \
    $TMPL/etc/dconf/db/jitas.d/click-policy

dconf update

# ------------------------------------------------------------------------------
# x11vnc autostart
# ------------------------------------------------------------------------------
out <<< "x11vnc autostart..."

wget -O /usr/local/bin/vnc-start \
    $TMPL/usr/local/bin/vnc-start
wget -O /etc/xdg/autostart/vnc.desktop \
    $TMPL/etc/xdg/autostart/vnc.desktop

chmod +x /usr/local/bin/vnc-start

# ------------------------------------------------------------------------------
# user jitas
# ------------------------------------------------------------------------------
out <<< "jitas account..."

# adduser jitas
id jitas 2>/dev/null || adduser jitas --disabled-password --gecos ""

# autostart desktop for jitas
[[ -f /home/jitas/.bashrc ]] || false

grep 'exec startx' /home/jitas/.bashrc || cat >>/home/jitas/.bashrc <<EOF

if [[ -z \$DISPLAY ]] && [[ \$(tty) = /dev/tty1 ]]; then
    exec startx
    exit
fi
EOF

# disable some autostarted applications for jitas
mkdir -p /home/jitas/.config/autostart
wget -O /home/jitas/.config/autostart/mate-power-manager.desktop \
    $TMPL/home/jitas/.config/autostart/mate-power-manager.desktop
wget -O /home/jitas/.config/autostart/mate-screensaver.desktop \
    $TMPL/home/jitas/.config/autostart/mate-screensaver.desktop
wget -O /home/jitas/.config/autostart/nm-applet.desktop \
    $TMPL/home/jitas/.config/autostart/nm-applet.desktop
chown jitas:jitas /home/jitas/.config/autostart -R

# vnc password
mkdir -p /home/jitas/.vnc
PASSWD=$(pwgen -B 12)
x11vnc -storepasswd $PASSWD /home/jitas/.vnc/passwd
chown jitas:jitas /home/jitas/.vnc -R

# ------------------------------------------------------------------------------
# autologin on tty1
# ------------------------------------------------------------------------------
mkdir -p /etc/systemd/system/getty@tty1.service.d
wget -O /etc/systemd/system/getty@tty1.service.d/override.conf \
    $TMPL/etc/systemd/system/getty@tty1.service.d/override.conf
systemctl daemon-reload

# if this is a reinstall time then reboot is needed
if pgrep -u jitas >/dev/null; then
    ACTIVE_SESSION=true
else
    systemctl restart getty@tty1.service
fi

# ------------------------------------------------------------------------------
# self-signed certificates
# ------------------------------------------------------------------------------
# the CA key and the CA certificate
[[ ! -d "/root/jitas_ssl" ]] && mkdir /root/jitas_ssl

if [[ ! -f "/root/jitas_ssl/jitas_CA.pem" ]]; then
    cd /root/jitas_ssl
    rm -f jitas-CA.key

    DATE=$(date +"%Y%m%d%H%M%S")
    openssl req -nodes -new -x509 -days 10950 \
        -keyout jitas-CA.key -out jitas-CA.pem \
        -subj "/O=jitas/OU=CA/CN=jitas $DATE-$RANDOM"
fi

# self-signed certificate for the jitas domain
cd /root/jitas_ssl
rm -f /root/jitas_ssl/ssl-jitas.*

# the extension file for multiple hosts:
cat >ssl-jitas.ext <<EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
EOF

HOSTNAME_SHORT=$(hostname)
HOSTNAME_FQDN=$(hostname -f)

echo "DNS.1 = $HOSTNAME_SHORT" >>ssl-jitas.ext

if [[ -n "$HOSTNAME_FQDN" ]] && [[ "$HOSTNAME_SHORT" != "$HOSTNAME_FQDN" ]]
then
    echo "DNS.2 = $HOSTNAME_FQDN" >>ssl-jitas.ext
else
    HOSTNAME_FQDN=$HOSTNAME_SHORT
fi

i=1
for ip in $(hostname -I); do
    echo "IP.$i = $ip" >>ssl-jitas.ext
    ((i = i + 1))
done

# the dodo key and the dodo certificate
openssl req -nodes -newkey rsa:2048 \
    -keyout ssl-jitas.key -out ssl-jitas.csr \
    -subj "/O=jitas/OU=TLS/CN=$HOSTNAME_FQDN"
openssl x509 -req -CA jitas-CA.pem -CAkey jitas-CA.key -CAcreateserial \
    -days 10950 -in ssl-jitas.csr -out ssl-jitas.pem \
    -extfile ssl-jitas.ext

# copy into /etc/ssl
cp ssl-jitas.pem /etc/ssl/certs/
cp ssl-jitas.key /etc/ssl/private/

# ------------------------------------------------------------------------------
# websockify
# ------------------------------------------------------------------------------
wget -O /usr/local/sbin/websockify-unsecure \
    $TMPL/usr/local/sbin/websockify-unsecure
chmod u+x /usr/local/sbin/websockify-unsecure

wget -O /usr/local/sbin/websockify-secure \
    $TMPL/usr/local/sbin/websockify-secure
chmod u+x /usr/local/sbin/websockify-secure

wget -O /etc/systemd/system/websockify-unsecure.service \
    $TMPL/etc/systemd/system/websockify-unsecure.service
wget -O /etc/systemd/system/websockify-secure.service \
    $TMPL/etc/systemd/system/websockify-secure.service

systemctl daemon-reload
systemctl enable websockify-unsecure.service
systemctl start websockify-unsecure.service
systemctl enable websockify-secure.service
systemctl start websockify-secure.service

# ------------------------------------------------------------------------------
# novnc
# ------------------------------------------------------------------------------
if [[ -d "/var/www/novnc" ]]; then
    cd /var/www/novnc
    git pull
else
    git clone --depth=1 https://github.com/novnc/noVNC.git /var/www/novnc
fi

# ------------------------------------------------------------------------------
# nginx
# ------------------------------------------------------------------------------
cp /root/jitas_ssl/jitas_CA.pem /var/www/html/jitas-ca.pem
wget -O /var/www/html/welcome.html $TMPL/var/www/html/welcome.html
wget -O /etc/nginx/sites-available/jitas.conf \
    $TMPL/etc/nginx/sites-available/jitas.conf

ln -sf ../sites-available/jitas.conf /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

systemctl restart nginx

# ------------------------------------------------------------------------------
# certbot
# ------------------------------------------------------------------------------
mkdir -p /etc/systemd/system/certbot.service.d
wget -O /etc/systemd/system/certbot.service.d/override.conf \
    $TMPL/etc/systemd/system/certbot.service.d/override.conf

systemctl daemon-reload

# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
END_TIME=$(date +%s)
DURATION=$(date -u -d "0 $END_TIME seconds - $START_TIME seconds" +"%H:%M:%S")
COMPLETED=true

# vim: tw=80 ts=4 sw=4 sts=4 et
